[package]
name = "RustStudy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "demo"
path = "src/lib.rs"

[dependencies]
rand="0.3.14"
humantime = "2.1.0"
chrono = "0.4.24"